FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build


FROM nginxinc/nginx-unprivileged:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

USER root
RUN chown -R nginx:nginx /etc/nginx/conf.d/default.conf
USER nginx

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]