FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci --prefer-offline --no-audit --legacy-peer-deps && npm cache clean --force

COPY . .

ENV NODE_OPTIONS="--max-old-space-size=2048"
RUN npm run build


FROM nginxinc/nginx-unprivileged:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

USER root
RUN chown -R nginx:nginx /etc/nginx/conf.d/default.conf
USER nginx

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]