FROM node:20-alpine

ENV NODE_ENV=production
WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev --prefer-offline --no-audit && npm cache clean --force

COPY src ./src
COPY database ./database
RUN chown -R node:node /app

EXPOSE 4000
USER node

CMD ["npm", "start"]
